[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; N16R8 = 16MB flash, 8MB PSRAM (Octal SPI)
board_build.flash_size = 16MB
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

monitor_speed = 115200
upload_speed = 921600

board_build.embed_txtfiles = data/index.html
